:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[ceres__shopbuildersettingshandler]]
= ShopBuilderSettingsHandler

Maps the routing settings from IO to Ceres. This allows us to set routing settings in the ShopBuilder.



===== Namespace

`Ceres\ShopBuilder\Handler`

===== Extends
xref:stable7@interface::Shopbuilder.adoc#shopbuilder_helper_mappablesettingshandler[`MappableSettingsHandler`]

===== Implements
xref:stable7@interface::Shopbuilder.adoc#shopbuilder_contracts_globalsettingshandler[`GlobalSettingsHandler`]



.Properties
|===
|Type |Name |Description

|link:http://php.net/array[`array`^]
a|`$mappings`
|Maps the Ceres settings to the IO settings.|link:http://php.net/array[`array`^]
a|`$casts`
|Decides what datatype the settings should be casted as.|link:http://php.net/array[`array`^]
a|`$enabledRoutes`
|Contains all enabled routes from the plugin config.
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#readrouting_homeenableroute]
----

public readRouting_HomeEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_homeenableroute]
----

public writeRouting_HomeEnableRoute($enableHomeRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableHomeRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_basketenableroute]
----

public readRouting_BasketEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_basketenableroute]
----

public writeRouting_BasketEnableRoute($enableBasketRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableBasketRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_checkoutenableroute]
----

public readRouting_CheckoutEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_checkoutenableroute]
----

public writeRouting_CheckoutEnableRoute($enableCheckoutRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableCheckoutRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_myaccountenableroute]
----

public readRouting_MyAccountEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_myaccountenableroute]
----

public writeRouting_MyAccountEnableRoute($enableMyAccountRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableMyAccountRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_searchenableroute]
----

public readRouting_searchEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_searchenableroute]
----

public writeRouting_searchEnableRoute($enableSearchRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableSearchRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_confirmationenableroute]
----

public readRouting_ConfirmationEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_confirmationenableroute]
----

public writeRouting_ConfirmationEnableRoute($enableConfirmationRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableConfirmationRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_loginenableroute]
----

public readRouting_LoginEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_loginenableroute]
----

public writeRouting_LoginEnableRoute($enableLoginRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableLoginRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_registerenableroute]
----

public readRouting_RegisterEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_registerenableroute]
----

public writeRouting_RegisterEnableRoute($enableRegisterRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableRegisterRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_cancellationrightsenableroute]
----

public readRouting_CancellationRightsEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_cancellationrightsenableroute]
----

public writeRouting_CancellationRightsEnableRoute($enableCancellationRightsRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableCancellationRightsRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_cancellationformenableroute]
----

public readRouting_CancellationFormEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_cancellationformenableroute]
----

public writeRouting_CancellationFormEnableRoute($enableCancellationFormRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableCancellationFormRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_legaldisclosureenableroute]
----

public readRouting_LegalDisclosureEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_legaldisclosureenableroute]
----

public writeRouting_LegalDisclosureEnableRoute($enableLegalDisclosureRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableLegalDisclosureRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_privacypolicyenableroute]
----

public readRouting_PrivacyPolicyEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_privacypolicyenableroute]
----

public writeRouting_PrivacyPolicyEnableRoute($enablePrivacyPolicyRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enablePrivacyPolicyRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_gtcenableroute]
----

public readRouting_GtcEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_gtcenableroute]
----

public writeRouting_GtcEnableRoute($enableGtcRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableGtcRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_contactenableroute]
----

public readRouting_ContactEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_contactenableroute]
----

public writeRouting_ContactEnableRoute($enableContactRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableContactRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_wishlistenableroute]
----

public readRouting_WishListEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_wishlistenableroute]
----

public writeRouting_WishListEnableRoute($enableWishListRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableWishListRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_changemailenableroute]
----

public readRouting_ChangeMailEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_changemailenableroute]
----

public writeRouting_ChangeMailEnableRoute($enableWishListRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableWishListRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_passwordresetenableroute]
----

public readRouting_PasswordResetEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_passwordresetenableroute]
----

public writeRouting_PasswordResetEnableRoute($enableWishListRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableWishListRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_newsletteroptoutenableroute]
----

public readRouting_NewsletterOptOutEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_newsletteroptoutenableroute]
----

public writeRouting_NewsletterOptOutEnableRoute($enableWishListRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableWishListRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_orderreturnenableroute]
----

public readRouting_OrderReturnEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_orderreturnenableroute]
----

public writeRouting_OrderReturnEnableRoute($enableWishListRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enableWishListRoute`
|If true, enable the route.
|===


[source%nowrap, php, subs=+macros]
[#readrouting_pagenotfoundenableroute]
----

public readRouting_PageNotFoundEnableRoute():link:http://php.net/bool[bool^]

----





Check if route is enabled or disabled.

[source%nowrap, php, subs=+macros]
[#writerouting_pagenotfoundenableroute]
----

public writeRouting_PageNotFoundEnableRoute($enablePageNotFoundRoute):link:http://php.net/string[string^]

----





Enable or disable the route.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/bool[`bool`^]
a|`$enablePageNotFoundRoute`
|If true, enable the route.
|===


