:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[ceres__barcodedatafieldprovider]]
= BarcodeDataFieldProvider

This class is a data field provider centered about the topic of bar codes.
It is used to enable placeholders for dynamic data in the shop builders text widget.
Please refer to the parent class for more information about DataFieldProviders.
Please refer to https://developers.plentymarkets.com/dev-doc/result-fields-ceres for more information about
the data fields.



===== Namespace

`Ceres\ShopBuilder\DataFieldProvider\Item`

===== Extends
xref:stable7@interface::Shopbuilder.adoc#shopbuilder_providers_datafieldprovider[`DataFieldProvider`]




.Properties
|===
|Type |Name |Description

|xref:stable7@interface::Item.adoc#item_models_barcode[`Barcode`]
a|`$barcode`
|
|===


===== Methods

[source%nowrap, php]
[#__construct]
----

public __construct($barcode):void

----









.*Parameters*
|===
|Type |Name |Description
|         xref:5.0.0@plugin-::.adoc#[``]
a|`$barcode`
|
|===


[source%nowrap, php]
[#register]
----

public register():void

----







Registers item data fields for use in the shop builder.

