:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[ceres__propertygroupdatafieldprovider]]
= PropertyGroupDataFieldProvider

This class is a data field provider centered about the topic of property groups.
It divides it&#039;s data into groups and single properties and delegates to child providers.
It is used to enable placeholders for dynamic data in the shop builders text widget.
Please refer to the parent class for more information about DataFieldProviders.
Please refer to https://developers.plentymarkets.com/dev-doc/result-fields-ceres for more information about
the data fields.



===== Namespace

`Ceres\ShopBuilder\DataFieldProvider\Item`

===== Extends
xref:stable7@interface::Shopbuilder.adoc#shopbuilder_providers_datafieldprovider[`DataFieldProvider`]




.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$noneGroupId`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$properties`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$groupNames`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#register]
----

public register()

----





Registers item data fields for use in the shop builder.

