:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[ceres__widgetdatafactory]]
= WidgetDataFactory





===== Namespace

`Ceres\Widgets\Helper\Factories`





.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$data`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#make]
----

public static make($identifier):xref:Ceres/Widgets/Helper/Factories/WidgetDataFactory.adoc#[WidgetDataFactory]

----





Create a new widget factory instance.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$identifier`
|Unique identifier of the widget.
|===


[source%nowrap, php, subs=+macros]
[#withlabel]
----

public withLabel($label):xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Set a label for this widget. Will be translated.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$label`
|Label of the widget to be displayed in the shop builder
|===


[source%nowrap, php, subs=+macros]
[#withpreviewimageurl]
----

public withPreviewImageUrl($previewImageUrl):xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Set the url of a preview image for the widget.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$previewImageUrl`
|
|===


[source%nowrap, php, subs=+macros]
[#withtype]
----

public withType($type):xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Set the type of the widget.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$type`
|Type of the widget
|===


[source%nowrap, php, subs=+macros]
[#withcategory]
----

public withCategory($category):xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Add a category for the widget. A widget might be assigned to multiple categories.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$category`
|
|===


[source%nowrap, php, subs=+macros]
[#withposition]
----

public withPosition($position):xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Set the position of the widget.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$position`
|Position of the widget
|===


[source%nowrap, php, subs=+macros]
[#withmaxperpage]
----

public withMaxPerPage($maxPerPage):xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Limit the amount of times a widget can be placed on a content.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/int[`int`^]
a|`$maxPerPage`
|Maximum allowed amount of instances of the widget on a content
|===


[source%nowrap, php, subs=+macros]
[#withallowednestingtypes]
----

public withAllowedNestingTypes($allowedTypes):xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Limits the widget types that you can drop into this widget.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$allowedTypes`
|
|===


[source%nowrap, php, subs=+macros]
[#withdeprecated]
----

public withDeprecated():xref:Ceres/Widgets/Helper/Factories.adoc#[Factories]

----





Set the widget as deprecated.

[source%nowrap, php, subs=+macros]
[#toarray]
----

public toArray():link:http://php.net/array[array^]

----





Get widget data.

