:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[ceres__widgetsettingsfactory]]
= WidgetSettingsFactory





===== Namespace

`Ceres\Widgets\Helper\Factories`





.Properties
|===
|Type |Name |Description

|         xref:5.0.0@plugin-::.adoc#[``]
a|`$settings`
||         xref:5.0.0@plugin-::.adoc#[``]
a|`$pointer`
|
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#inherit]
----

public static inherit($parentWidgetClass):xref:Ceres/Widgets/Helper/Factories/WidgetSettingsFactory.adoc#[WidgetSettingsFactory]

----





Create a new factory instance and initialize values from given widget class.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$parentWidgetClass`
|
|===


[source%nowrap, php, subs=+macros]
[#create]
----

public static create($data = []):xref:Ceres/Widgets/Helper/Factories/WidgetSettingsFactory.adoc#[WidgetSettingsFactory]

----





Create a new factory instance with initial values.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/array[`array`^]
a|`$data`
|
|===


[source%nowrap, php, subs=+macros]
[#createsetting]
----

public createSetting($key):xref:Ceres/Widgets/Helper/Factories/Settings/BaseSettingFactory.adoc#[BaseSettingFactory]

----





Create a generic widget settings entry.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|The key of the new settings entry. If key already exists, previous entry will be overridden.
|===


[source%nowrap, php, subs=+macros]
[#createcontainer]
----

public createContainer($key):xref:Ceres/Widgets/Helper/Factories/Settings/ContainerSettingFactory.adoc#[ContainerSettingFactory]

----





Create a container entry which may contain nested settings.

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createverticalcontainer]
----

public createVerticalContainer($key):xref:Ceres/Widgets/Helper/Factories/Settings/ContainerSettingFactory.adoc#[ContainerSettingFactory]

----





Create a vertical container

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createhorizontalcontainer]
----

public createHorizontalContainer($key):xref:Ceres/Widgets/Helper/Factories/Settings/ContainerSettingFactory.adoc#[ContainerSettingFactory]

----





Create a horizontal container

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createtext]
----

public createText($key):xref:Ceres/Widgets/Helper/Factories/Settings/TextSettingFactory.adoc#[TextSettingFactory]

----





Create a text input setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createcheckbox]
----

public createCheckbox($key):xref:Ceres/Widgets/Helper/Factories/Settings/CheckboxSettingFactory.adoc#[CheckboxSettingFactory]

----





Create a checkbox setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createcolorpalette]
----

public createColorPalette():xref:Ceres/Widgets/Helper/Factories/Settings/ColorPaletteSettingFactory.adoc#[ColorPaletteSettingFactory]

----





Create a color setting

[source%nowrap, php, subs=+macros]
[#createdate]
----

public createDate($key):xref:Ceres/Widgets/Helper/Factories/Settings/DateSettingFactory.adoc#[DateSettingFactory]

----





Create a date input setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createfile]
----

public createFile($key):xref:Ceres/Widgets/Helper/Factories/Settings/FileSettingFactory.adoc#[FileSettingFactory]

----





Create a file picker setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createtextarea]
----

public createTextarea($key):xref:Ceres/Widgets/Helper/Factories/Settings/TextareaSettingFactory.adoc#[TextareaSettingFactory]

----





Create a textarea input setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createnumber]
----

public createNumber($key):xref:Ceres/Widgets/Helper/Factories/Settings/BaseSettingFactory.adoc#[BaseSettingFactory]

----







.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createdouble]
----

public createDouble($key):xref:Ceres/Widgets/Helper/Factories/Settings/DoubleSettingFactory.adoc#[DoubleSettingFactory]

----





Create a double input setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createselect]
----

public createSelect($key):xref:Ceres/Widgets/Helper/Factories/Settings/SelectSettingFactory.adoc#[SelectSettingFactory]

----





Create a dropdown setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createsuggestion]
----

public createSuggestion($key):xref:Ceres/Widgets/Helper/Factories/Settings/SuggestionSettingFactory.adoc#[SuggestionSettingFactory]

----





Create a dropdown setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createcategory]
----

public createCategory($key):xref:Ceres/Widgets/Helper/Factories/Settings/CategorySettingFactory.adoc#[CategorySettingFactory]

----





Create a category select setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createcolor]
----

public createColor($key):xref:Ceres/Widgets/Helper/Factories/Settings/BaseSettingFactory.adoc#[BaseSettingFactory]

----







.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createslider]
----

public createSlider($key):xref:Ceres/Widgets/Helper/Factories/Settings/SliderSettingFactory.adoc#[SliderSettingFactory]

----





Create a slider setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createcheckboxgroup]
----

public createCheckboxGroup($key):xref:Ceres/Widgets/Helper/Factories/Settings/CheckboxGroupSettingFactory.adoc#[CheckboxGroupSettingFactory]

----





Create a checkbox group setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createradiogroup]
----

public createRadioGroup($key):xref:Ceres/Widgets/Helper/Factories/Settings/RadioGroupSettingFactory.adoc#[RadioGroupSettingFactory]

----





Create a checkbox group setting

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createurl]
----

public createUrl($key):xref:Ceres/Widgets/Helper/Factories/Settings/UrlSettingFactory.adoc#[UrlSettingFactory]

----





Create a url picker

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createnoteeditor]
----

public createNoteEditor($key):xref:Ceres/Widgets/Helper/Factories/Settings/EditorSettingFactory.adoc#[EditorSettingFactory]

----







.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createcodeeditor]
----

public createCodeEditor($key):xref:Ceres/Widgets/Helper/Factories/Settings/EditorSettingFactory.adoc#[EditorSettingFactory]

----







.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$key`
|
|===


[source%nowrap, php, subs=+macros]
[#createcustomclass]
----

public createCustomClass():xref:Ceres/Widgets/Helper/Factories/Settings/CustomClassSettingFactory.adoc#[CustomClassSettingFactory]

----







[source%nowrap, php, subs=+macros]
[#createicon]
----

public createIcon():xref:Ceres/Widgets/Helper/Factories/Settings/IconSettingFactory.adoc#[IconSettingFactory]

----







[source%nowrap, php, subs=+macros]
[#createheight]
----

public createHeight():xref:Ceres/Widgets/Helper/Factories/Settings/HeightSettingFactory.adoc#[HeightSettingFactory]

----







[source%nowrap, php, subs=+macros]
[#createbuttonsize]
----

public createButtonSize():xref:Ceres/Widgets/Helper/Factories/Settings/ButtonSizeSettingFactory.adoc#[ButtonSizeSettingFactory]

----







[source%nowrap, php, subs=+macros]
[#createalignment]
----

public createAlignment():xref:Ceres/Widgets/Helper/Factories/Settings/AlignmentSettingFactory.adoc#[AlignmentSettingFactory]

----







[source%nowrap, php, subs=+macros]
[#toarray]
----

public toArray()

----







