:table-caption!:
:example-caption!:
:source-highlighter: prettify
:sectids!:
[[ceres__defaultcontactpreset]]
= DefaultContactPreset

This is a preset for ShopBuilder contents. Presets can be applied during content creation to generate a default content with predefined and configured widgets. +
This particular preset generates a page for viewing the shop&#039;s contact information and location. It contains: +
- InlineTextWidget +
- SeparatorWidget +
- TwoColumnWidget +
- ContactDetailsWidget +
- GoogleMapsWidget +
- MailFormWidget +
- TextInputWidget +
- MailInputWidget +
- TextAreaWidget +
- AcceptPrivacyPolicyWidget



===== Namespace

`Ceres\Widgets\Presets`


===== Implements
xref:stable7@interface::Shopbuilder.adoc#shopbuilder_contracts_contentpreset[`ContentPreset`]



.Properties
|===
|Type |Name |Description

|xref:Ceres/Config/CeresConfig.adoc#[`CeresConfig`]
a|`$config`
|| xref:stable7@interface::Miscellaneous.adoc#miscellaneous_translation_translator[`Translator`]
a|`$translator`
||xref:Ceres/Widgets/Helper/Factories/PresetWidgetFactory.adoc#[`PresetWidgetFactory`]
a|`$backgroundWidget`
|The background widget
|===


===== Methods

[source%nowrap, php, subs=+macros]
[#getwidgets]
----

public getWidgets():link:http://php.net/mixed[mixed^]

----





Get the widget configurations of the presets to be assigned to the created content.

[source%nowrap, php, subs=+macros]
[#createbackground]
----

public createBackground($preset):xref:Ceres/Widgets/Helper/Factories/PresetWidgetFactory.adoc#[PresetWidgetFactory]

----





Creates a preconfigured white background widget

.*Parameters*
|===
|Type |Name |Description
|xref:Ceres/Widgets/Helper/PresetHelper.adoc#[`PresetHelper`]
a|`$preset`
|
|===


[source%nowrap, php, subs=+macros]
[#setbackgroundwidgetsettings]
----

public setBackgroundWidgetSettings($widget):xref:Ceres/Widgets/Helper/Factories/PresetWidgetFactory.adoc#[PresetWidgetFactory]

----





Configures a background widget

.*Parameters*
|===
|Type |Name |Description
|xref:Ceres/Widgets/Helper/Factories/PresetWidgetFactory.adoc#[`PresetWidgetFactory`]
a|`$widget`
|
|===


[source%nowrap, php, subs=+macros]
[#createwidget]
----

public createWidget($identifier):xref:Ceres/Widgets/Helper/Factories/PresetWidgetFactory.adoc#[PresetWidgetFactory]

----





Creates the background widget with an identifier

.*Parameters*
|===
|Type |Name |Description
|link:http://php.net/string[`string`^]
a|`$identifier`
|
|===


